# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lumedeir < lumedeir@student.42sp.org.br    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/20 09:58:22 by lumedeir          #+#    #+#              #
#    Updated: 2023/10/16 11:11:47 by lumedeir         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# The name of the executable
NAME = push_swap
# Compilation flags
CC = gcc
CFLAGS = -Wall -Wextra -Werror -g3
# Directories
INCLUDE = -I./includes
LIBFT = ./Libft
BUILD = ./objs/

# Source files mandatory
SRC =	src/check_args.c src/error.c \
		src/init_stacks.c src/push_swap.c src/moves/push.c\
		src/moves/swap.c src/moves/rotate.c src/moves/reverse_rotate.c \
		src/sort.c src/get_index.c src/big_sort.c \
		src/search_minimum.c src/utils_stacks.c\

OBJ = $(SRC:.c=.o)

# Color codes for terminal output
PURPLE = \033[1;35m
CYAN= \033[0;36m

# The default target calling for the executable
all : $(NAME)

# The target to build the mandatory part
$(NAME) : $(OBJ)
	@make -C $(LIBFT) --silent
	@$(CC) $(OBJ) $(CFLAGS) $(LIBFT)/libft.a -o $(NAME)
	@echo "$(CYAN)The Makefile of [$(PURPLE)PUSH_SWAP$(CYAN)] has been compiled!🤠"


# Cleans object files and dependencies
clean:
		@make clean -C $(LIBFT) --silent
		@rm -rf $(OBJ)

fclean: clean
		@echo "Cleaning all... 🧹"
		@make fclean -C $(LIBFT) --silent
		@rm -f $(NAME)
		@echo "✨ Cleaning complete! ✨"

# Cleans everything generated by the Makefile and rebuild all
re: fclean all

# Phony targets
.PHONY: all clean fclean re